# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 分享技术,品味人生 # ex. I m Chuan
subtitle: 其实我是一个程序员
name: 纯洁的微笑 # ex. DONGChuan
email: ronjony@sina.com
github_url: https://github.com/ronjony # ex. https://github.com/DONGChuan
description: 一个纯洁的程序员，一个还在一线写代码的研发总监。
keywords: ronjony, 纯洁的微笑, Spring, SpringBoot, SpringCloud, MongoDB, Jvm, 生活故事, 架构
encoding: "utf-8"
favicon: favicon.png # Image must be in assets/images
repository: ronjony/ronjony.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://www.mooooc.com
enforce_ssl: mooooc.com

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

  -
    href: /scala.html
    label: scala

  -
    href: /java.html
    label: java

  -
    href: /archives.html
    label: Archives

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words
labels:

  -
    href: /share/2017/10/01/resource-sharing.html
    name: 学习资源

  -
    href: https://wx.xiaomiquan.com/mweb/views/joingroup/join_group.html?group_id=881415141512&secret=gg9ch1oco389vka95d6zb18a8x5x804n&user_id=51122215822184
    name: 知识星球

  -
    href: /life.html
    name: 生活故事

  -
    href: /arch.html
    name: 架构之路
    
  -
    href: /jvm.html
    name: Jvm

  -
    href: /open-source.html
    name: Open-Source   

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: ityouknow
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ityouknow
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ityouknow
    repo: blog-comments
    clientID: 61bfc53d957e74e78f8f
    clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true